### ISSUE TITLE
Sidebar content appears at end of content

### ISSUE THREAD

**Issue by tylerknowsnothing** [lmika/sidebar-for-tiny-theme#1]
Using a clean custom theme I followed the instructions to add the sidebar and everything appears to work as expected, but the recommendations appear under the content and not at the side. Screenshot for reference. Any suggestions would be appreciated. Thanks!

![image](https://github.com/user-attachments/assets/42bbf3be-801d-4df3-ab21-c7a63bdffb88)

**Comment by lmika** [comment]
Hi @tylerregas, I'm suspecting something to do with the styling, the post list might not be picking up the correct CSS rules. Would you mind sending a link to this page so I can take a look at the HTML? Also, can you let me know which version of Tiny Theme you are using?

**Comment by tylerknowsnothing** [comment]
Sure thing :) Here's my site link: https://tylerknowsnothing.com

I'm using the latest version of Tiny I think. 2.8.5 with Sidebar 1.1.1. If you need anything else, just let me know. Also, I haven't made any changes to the CSS in this custom theme. I thought an adjustment to the content width had maybe been the culprit or adding a header image, so I just started fresh. 

Thanks!

**Comment by lmika** [comment]
Ah, okay. I think I see the problem. Looking at your page source, it looks like the sidebar is a child of `<div class="post_list">`, in `body > div.page-content > div.wrapper > div.posts`

![Screenshot 2024-08-31 at 9 14 48 AM](https://github.com/user-attachments/assets/519e107f-2778-4e26-9cc3-0b9d23c90fbc)

If I remember correctly, there was a version of Sidebar, probably before the plugin or with an old version of Tiny Theme, where this was necessary. The recent version of Sidebar takes advantage of hooks added to Tiny theme and now has it placed as a direct descendant of page content, `body > div.page-content`, below `div.wrapper`:

![Screenshot 2024-08-31 at 9 14 30 AM](https://github.com/user-attachments/assets/a82299e3-417e-4ac7-9f87-2ea419bf1e8b)

Did you add the sidebar in a `microhook-after-post-list.html` micro-hook, as per [this blog post](https://lmika.org/2024/03/14/adding-a-sidebar.html)? If so, you can remove the sidebar from that Micro-hook, along with the CSS, and leave it up to the plugin.  Otherwise, let me know if you've made any other template changes.

**Comment by tylerknowsnothing** [comment]
I did see that post, but all I did was create the template below as instructed, saved it and allowed it to load, then added the recommendations code. I did this in a clean template. Without the template, the default recommendations also appear at the bottom. 

I also currently don't fully understand how to add microhooks yet, either 🤣 

`layouts/partials/sidebar.html`

[TIME PASSES]

Okay, as I was cruising around the template files I took a peek at config.json which has a paginate directive set to 20. I changed that to 5 and the sidebar appeared as a sidebar instead of under the post list! 

![image](https://github.com/user-attachments/assets/8880bf27-08ee-4fc6-9e09-c1765d5d704f)

**Comment by lmika** [comment]
Huh, that's interesting. Can you try changing that back to 20 to see if the sidebar stays on the side?

**Comment by tylerknowsnothing** [comment]
Switched it back to 20 and the sidebar jumped back to the bottom. Funky.

**Comment by lmika** [comment]
That's really strange. I've tried adjusting this file between 5 and 20 on a test blog and the sidebar is staying on the right side.

Maybe what I can suggest is seeing whether or not you can adjust the main template for Tiny Theme.  If you go to Micro.blog, in Designs -> Edit Themes -> (name of your custom theme), then on the left side, see if there's a template with the name "layouts/_default/baseof.html".  If you do find it, see whether or not it matches the value of this file:

https://raw.githubusercontent.com/MattSLangford/Tiny-Theme-for-Micro.blog/main/layouts/_default/baseof.html

Specifically, it needs to have the following snippet in place:

```
  <div class="page-content">
    <div class="wrapper">
      {{ block "main" . }}{{ end }}
    </div>
    {{ if templates.Exists "partials/microhook-below-wrapper.html" }}
          {{ partial "microhook-below-wrapper.html" . }}
    {{ end }}
  </div>
```

If it doesn't, then I'd suggest replacing what you have in Micro.blog with the contents of the linked file. This is from Tiny Theme's Github source code, so if there's been no changes made, it should match this.

One other thing you could try is uninstalling the Sidebar for Tiny Theme plugin, then reinstalling it again.

**Comment by lmika** [comment]
One other thing you can try is rebuilding the blog from scratch, by going to "Account" in Micro.blog, then clicking the "View Logs" link and click the "Rebuild ..." button on the top-left.

**Comment by tylerknowsnothing** [comment]
I have the snippet in there. This is the complete file...

```
<!DOCTYPE html>
<html lang="en">

{{ partial "head.html" . }}

<body>
  {{ partial "header.html" . }}

  <div class="page-content">
    <div class="wrapper">
      {{ block "main" . }}{{ end }}
    </div>
    {{ if templates.Exists "partials/microhook-below-wrapper.html" }}
          {{ partial "microhook-below-wrapper.html" . }}
    {{ end }}
  </div>
  {{ partial "footer.html" . }}

  {{ range .Site.Params.plugins_js }}
  <script src="{{ . }}"></script>
  {{ end }}

  {{ if templates.Exists "partials/microhook-before-closing-body.html" }}
  {{ partial "microhook-before-closing-body.html" . }}
  {{ end }}
</body>

</html>
```

**Comment by lmika** [comment]
Ok, that's even stranger because that is the file that is expected. Maybe try uninstalling the Sidebar for Tiny Theme plugin and see if the sidebar disappears.

**Comment by tylerknowsnothing** [comment]
That template that I created will remain, correct? If not, I'll copy out the code first 😄

**Comment by lmika** [comment]
Yeah, that template looks correct so you don't need to do anything to it.

**Comment by tylerknowsnothing** [comment]
Before I reinstall it should I return the blog count to 20?

**Comment by lmika** [comment]
Yes, please restore it to what you'd like to set it to.

**Comment by tylerknowsnothing** [comment]
Yep. Still sends the sidebar content to the bottom with 20.

**Comment by lmika** [comment]
Ok, one other thing we could try: in Designs -> Edit Themes, do you see any instances of "Sidebar for Tiny Theme" in the Plugins section? As in:

![Screenshot 2024-08-31 at 11 42 34 AM](https://github.com/user-attachments/assets/09bbd5a5-79e7-4630-8a80-adfd8842c041)

If so, can you click on it and check to see what the value of "layouts/_default/baseof.html" is for that file?

**Comment by tylerknowsnothing** [comment]
I've reset it to 5 which works fine for me. This is working well for me. One note I should make is that I'm in Safari, so that could be a factor. I have to run an errand real quick now, but I can do more testing later with FF and Chrome. Hadn't thought of that until just now. 

I'd also like to figure out how to add bullet points to each line item, get links to a Featured category to appear for articles I'd like people to take a closer look at, and figure out how to get the OPML and JSON links to appear under the blogrolls. I've definitely got more tinkering and learning 😁

**Comment by tylerknowsnothing** [comment]
> Ok, one other thing we could try: in Designs -> Edit Themes, do you see any instances of "Sidebar for Tiny Theme" in the Plugins section? As in:
> 
> ![Screenshot 2024-08-31 at 11 42 34 AM](https://private-user-images.githubusercontent.com/3238909/363382691-09bbd5a5-79e7-4630-8a80-adfd8842c041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNjkzNDIsIm5iZiI6MTcyNTA2OTA0MiwicGF0aCI6Ii8zMjM4OTA5LzM2MzM4MjY5MS0wOWJiZDVhNS03OWU3LTQ2MzAtOGE4MC1hZGZkODg0MmMwNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzFUMDE1MDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzNlZGZkNzU2OGI1ZTU2MWE2YmFmMjJmMDdhNmFhY2IyMjQ3MGMxZDk1Y2UxMzFlOWQ2Y2RmNmMxODM4MWU2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cXN4Hrda-187VJk5m7MK8ffnAYVPJzbzzIrwRGN9VEw)
> 
> If so, can you click on it and check to see what the value of "layouts/_default/baseof.html" is for that file?

I don't see a plugins section on that page...

![image](https://github.com/user-attachments/assets/3872337f-7011-41e7-a31c-53ac351843b5)

**Comment by tylerknowsnothing** [comment]
I'll be back in about an hour 👍 Thanks so much!!

**Comment by lmika** [comment]
Ok, sounds good. I just check my blog in Safari and it appeared on the right as expected. I pretty sure it's got something to do with a bad version of the template somewhere.

Thanks for your help. Sorry that we didn't get to the bottom of this yet. Let me know if you see any other patterns in your testing.

**Comment by tylerknowsnothing** [comment]
I think what I'll do is just create a fresh template and see what happens. Before I do that, however, I'll restart Safari. It gets weird when it's been running for a while. I don't reboot very often, around once every 7-10 days, but I order to avoid some oddities in Safari I have to quit it every couple of days. It's been three since I last bounced this thing 🤣 I'll let you know if I figure out any new clues 👍

**Comment by lmika** [comment]
Hi @tylerregas, just wondering if you have any success with that fresh template.

**Comment by lmika** [comment]
Hi @tylerregas, I just visited your site and I can see that the sidebar is properly on the right, so I'll close this ticket for now. Feel free to raise another issue if have any further issues.

**Comment by tylerknowsnothing** [comment]
Thanks, Leon. Looking good now. Had to build the “featured” section manually for now but I think it looks good enough for now :) you’re the best!
